
cpp_files	:= main.cpp test.cpp

CFLAGS		:= -I.
CPPFLAGS	:= -I.
LFLAGS		:=

build_type	?= debug
binary_type	?= static_library
target		:= $(notdir $(CURDIR))

build_system := /u/thovhann/Desktop/gnu_make/tworkspace/trunk/build_system

include $(build_system)/main.mk
