
cpp_files	:= main.cpp

CFLAGS		:=
CPPFLAGS	:=
LFLAGS		:=

binary_type	:= shared_library
build_type	:= debug
target		:= $(notdir $(CURDIR))

build_system := /u/thovhann/Desktop/gnu_make/tworkspace/trunk/build_system

include $(build_system)/core/main.mk
