
cpp_files	:= main.cpp test.cpp

CFLAGS		:= -I.
CPPFLAGS	:= -I.
LFLAGS		:=

build_type	?= debug
binary_type	?= exe
target		:= $(notdir $(CURDIR))

build_system ?= /u/thovhann/Desktop/gnu_make/build_system
customer_dir ?= /u/thovhann/Desktop/gnu_make/product

include $(build_system)/main.mk

