
cpp_files	:= main.cpp

CFLAGS		:= 
CPPFLAGS	:= 
LFLAGS		:=

build_type	?= debug
binary_type	?= exe
target		:= $(notdir $(CURDIR))

build_system := /u/thovhann/Desktop/gnu_make/tworkspace/trunk/build_system

include $(build_system)/main.mk
